refactor: package.json 使用合成策略
FEMessage/create-nuxt-app pull request #138
Opened 2019-12-27 07:10 UTC by donaldshen

## Why
1. windows 下命令`eslint 'src/**/*.@(js|vue)'`会出错，原因是单引号不行，要改成双引号`eslint \"src/**/*.@(js|vue)\"`
2. 每次改 package.json，都得改三份；如果是改依赖，那还得改 yarn.lock

所以重构目标是：
1. 通用内容可以放在 framework/_package.json
2. 特定内容才放 framework-name/_package.json
3. 依赖版本直接通过 package.json 来锁定，大部分情况下应该直接使用 semver 下的最新依赖

## How
1. 抽离三个 _package.json 共同的内容到 framework/_package.json
2. 调整 saofile.js 的构建策略：
  a. 先复制基础模板 framework 的内容到目标地址
  b. 改名 _package.json => package.json （防止被后续拷贝覆盖）
  c. 复制特定模板 framework-name 的内容到目标地址
  d. 合并内容 _package.json => package.json，并移除没用的 _package.json
  e. 后续步骤不变……
3. 移除所有 yarn.lock

## Test
1. 执行 yarn test:snapshot，快照只有一处不同：没了 yarn.lock
2. 查看 netlify 的 preview：一切正常

2019-12-27 07:21 UTC, eviIIt commented on package.json
> +    "node": ">=11.15.0"
Oops, netlify 的 node 版本只是 `10.18.0`

2019-12-30 07:00 UTC, levy9527 commented on template/framework/_package.json
> +  "authors": [
base 这个名称，体现一下。

2019-12-30 07:08 UTC, levy9527 requested changes

2019-12-30 07:08 UTC, levy9527 commented on generator/saofile.js
> +    // 这些配置文件在模板中是加了'_'前缀的（防止影响到本项目），移到生成的项目后要去掉前缀
补充注释：同时也防止这些文件无法发布至 npm。

2019-12-30 09:38 UTC, eviIIt approved these changes

2019-12-30 09:41 UTC, levy9527 approved these changes

2019-12-30 09:41 UTC, merged

2020-01-03 10:06 UTC, levy9527 commented
:tada: This PR is included in version 1.12.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@femessage/create-nuxt-app)
- [GitHub release](https://github.com/FEMessage/create-nuxt-app/releases/tag/untagged-89cf20827b5488fdf7da)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: