feat!: new template admin
FEMessage/create-nuxt-app pull request #142
Opened 2020-01-14 11:29 UTC by lianghx-319

## Why
Why is this change required? What problem does it solve?

## How
Describe your steps:
1. one step
2. two step...

You may use xmind or other mind map to show you logic

## Test
Show your test case

you'd better show `before` and `after` 

## Docs
It there requires a change to the documentation？

2020-01-15 08:53 UTC, donaldshen commented on bin/deploy/env.json
> +  "nuxt-multiple-spa": {},
是不是要删掉

2020-01-15 08:54 UTC, donaldshen commented on template.config.js
> +// const multiple = {
删掉呗

2020-01-15 08:56 UTC, donaldshen commented on template/framework-base/nuxt.config.js
> +const {getRouterBase} = require('./src/utils')
顺序调一下吧，不要看上去好像删了其实又没改

2020-01-15 09:02 UTC, donaldshen commented on template/framework-base/_package.json
> +    "core-js": "3.6.4",
有没有在项目试过 async/await？确定不需要 regenerator-runtime？

2020-01-15 09:06 UTC, lianghx-319 commented on template/framework-base/_package.json
> +    "core-js": "3.6.4",
试过了，在 store/index.js

2020-01-15 12:03 UTC, levy9527 requested changes

2020-01-15 12:03 UTC, levy9527 commented on template/modules/service/api/repository.js
> +
直接改成 crud 相应的单词 + list

2020-01-16 12:01 UTC, donaldshen approved these changes

2020-01-20 06:38 UTC, merged

2020-02-18 10:55 UTC, levy9527 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@femessage/create-nuxt-app)
- [GitHub release](https://github.com/FEMessage/create-nuxt-app/releases/tag/untagged-68d4b3ab4b341180bf22)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: