feat: upgrade a new pc template
FEMessage/create-nuxt-app pull request #143
Opened 2020-01-21 07:01 UTC by lianghx-319

BREAKING CHANGE: 更完善的管理后台布局样式
		 macOS 和 windows 统一的滚动条
		 基于项目实践的 XHR 拦截
		 基于 RESTful 最佳实践的 service 分层方案
		 更友好的鉴权，重新登录后会重定向到权限失效时的页面
		 默认对接 cloud-deepexi 的登录，菜单接口|
		 内置面包屑方案，支持动态面包屑
		 基于 deepexi design 的文字色彩方案
		 支持 svg-icon
		 支持 es optional-chaining 和 nullish-coalescing-operator

## Why
semantic release 需要 commit footer 中有 breaking change 字符才会 release major version

## Docs
更新模板的 README.md

2020-02-17 11:56 UTC, donaldshen approved these changes

2020-02-18 09:09 UTC, levy9527 requested changes

2020-02-18 09:09 UTC, levy9527 commented on template/framework-base/README.md
> +| APP_ID      | 如果需要对接 cloud-deepexi 则需要提供平台的产品应用 ID | 否       |        |                           |
尽量别出现这些字眼

2020-02-18 10:30 UTC, levy9527 approved these changes

2020-02-18 10:30 UTC, merged

2020-02-18 10:56 UTC, levy9527 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@femessage/create-nuxt-app)
- [GitHub release](https://github.com/FEMessage/create-nuxt-app/releases/tag/untagged-68d4b3ab4b341180bf22)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: