fix(admin): 完善 admin 模板
FEMessage/create-nuxt-app pull request #144
Opened 2020-02-17 10:06 UTC by lianghx-319

## Why
完善 admin 模板

## Features
- 使用 normalize.css 代替 reset.css
- 完善模板的 eslint
- 更新 README.me
- jsconfig 支持 vscode webpack 别名路径跳转 

## Attention
publish 之前 travis CI 需要清除 cache，同时确保 git commit 包含 breaking-change 等字符

2020-02-17 10:15 UTC, xrr2016 approved these changes

2020-02-17 10:49 UTC, donaldshen commented on template/modules/auth/middleware/auth.js
> + * @Last Modified time: 2020-02-17 16:46:31
这是咋完善的，手写吗？

2020-02-17 10:51 UTC, lianghx-319 commented on template/modules/auth/middleware/auth.js
> + * @Last Modified time: 2020-02-17 16:46:31
有模板的是手写的...

2020-02-17 10:52 UTC, donaldshen approved these changes

2020-02-18 09:11 UTC, levy9527 requested changes

2020-02-18 09:11 UTC, levy9527 commented on template/framework-base/nuxt.config.js
> +      '/deepexi-cloud': apiServer,
尽量别出现这些特定内容

2020-02-18 09:57 UTC, levy9527 approved these changes

2020-02-18 09:57 UTC, merged

2020-02-18 10:55 UTC, levy9527 commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@femessage/create-nuxt-app)
- [GitHub release](https://github.com/FEMessage/create-nuxt-app/releases/tag/untagged-68d4b3ab4b341180bf22)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: