refactor: api renamed services
FEMessage/create-nuxt-app pull request #163
Opened 2020-11-24 09:09 UTC by gd4Ark

## Why
api 不直观，改名为 services

## How
1. 将 api 目录和注入上下文的名字改名为 services
2. serverList 改名为 api

## Docs
修改 api 相关文档

2020-11-24 10:15 UTC, snowlocked approved these changes

2020-11-24 10:38 UTC, shoyuf approved these changes

2020-11-25 02:20 UTC, levy9527 requested changes

2020-11-25 02:20 UTC, levy9527 commented on template/framework-base/README.md
> +│   │   └── api.js  统一管理服务路径和 API version
两个改动：
1. api.js / repository.js 放到 common 子目录下
2. login/menus 的基本逻辑放到 basic.js
3. 通过 require.context 扫描代码（只扫描一层即可，后缀为 .js/.ts），让后续添加代码符合开闭原则

2020-11-25 06:52 UTC, shoyuf approved these changes

2020-11-25 07:12 UTC, levy9527 requested changes

2020-11-25 07:12 UTC, levy9527 commented on template/framework-base/README.md
> +this.$services.example.delete(ID)
1. 一个文字一个 scope，对象挂在 scope 
2. 再区分 default，default 的 key 就直接挂在 scope 下

2020-11-26 04:57 UTC, levy9527 commented on docs/api.md
> +如果文件中既有 `export default` 又有 `export const`，则会将 `export const` 挂在 scope 下。
`则会将 `export const` 挂在 scope 下。` 去掉

2020-11-26 04:57 UTC, levy9527 commented on docs/api.md
> +如果文件中有 `export default`，则会直接挂在这个 scope 下。
`则会直接挂在这个 scope 下。` 去掉

2020-11-26 04:58 UTC, levy9527 commented on docs/api.md
> +['uri','create','list','detail','update','delete']
给个链接

2020-11-26 05:04 UTC, levy9527 commented on template/modules/service/services/index.js
> +const serviceModules = require.context('./', false, /\.js|.ts$/)
链接到文档，把多余的注释去掉

2020-11-26 06:28 UTC, levy9527 approved these changes

2020-11-26 06:29 UTC, merged

2020-11-26 06:35 UTC, levy9527 commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@femessage/create-nuxt-app)
- [GitHub release](https://github.com/FEMessage/create-nuxt-app/releases/tag/untagged-5faf38bcb14650be595b)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: