feat: 增加nuxt + vant模板
FEMessage/create-nuxt-app pull request #52
Opened 2019-08-02 09:13 UTC by donaldshen

## Why
1. 客户需求
2. 旧的模板需要合并进来，方便维护

## How
参考commit记录

2019-08-02 09:34 UTC, levy9527 requested changes

2019-08-02 09:34 UTC, levy9527 commented on package.json
> +    "cac": "^6.5.2",
这个干嘛的

2019-08-02 09:34 UTC, levy9527 commented on template/frameworks/mobile/components/Copyright.vue
> +  </div>
这个组件不是有吗。关键是，文件名不对

2019-08-02 09:34 UTC, levy9527 commented on template/frameworks/mobile/mixins/auth.js
> +import cookie from 'js-cookie'
这个不应该去掉了吗

2019-08-02 09:34 UTC, levy9527 commented on template/frameworks/mobile/mixins/auth.js
> +import cookie from 'js-cookie'
应该是 middleware

2019-08-02 09:39 UTC, donaldshen commented on package.json
> +    "cac": "^6.5.2",
bin/cli.js用到，这里显式声明依赖。
之前正常是因为sao有引入cac，是隐式依赖

2019-08-02 11:16 UTC, merged

2019-08-05 07:15 UTC, levy9527 commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@femessage/create-nuxt-app)
- [GitHub release](https://github.com/FEMessage/create-nuxt-app/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: