refactor: 融合const/filters & mobile模板中的filters
FEMessage/create-nuxt-app pull request #57
Opened 2019-08-06 09:46 UTC by donaldshen

## Why
filters不适合在constant文件夹下

## How
1. 将mobile模板中的filters.js与constant/const/filters.js合并，也参考了秀域项目的实现
2. 新建filters模块，并添加到common配置中

## Test
1. 运行yarn build
2. 在release下的项目中执行yarn test，并通过
![image](https://user-images.githubusercontent.com/19591950/62525638-55616080-b86a-11e9-951e-025c2d19f8b2.png)

2019-08-06 12:16 UTC, lianghx-319 commented
文件位置变动需要更新一下 snapshot，不然 CI/CD 会 fail

2019-08-07 07:58 UTC, levy9527 requested changes

2019-08-07 07:58 UTC, levy9527 commented on template/frameworks/mobile/plugins/filter.js
> -  return '¥' + USPrice
那么 ¥ 这个符号怎么处理呢，这不是让功能缺失了？而且也没有测试

2019-08-15 11:49 UTC, donaldshen commented on template/frameworks/mobile/plugins/filter.js
> -  return '¥' + USPrice
已添加测试，但测试需要依赖`full-icu`这个包（约53m大小）。我把开启测试的步骤写到test里了，用户想测可以自行安装此依赖。
这次添加测试的主要目的是提供用法示例。

2019-08-30 06:49 UTC, levy9527 approved these changes

2019-08-30 06:49 UTC, merged

2019-08-30 08:19 UTC, levy9527 commented
:tada: This PR is included in version 1.6.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@femessage/create-nuxt-app)
- [GitHub release](https://github.com/FEMessage/create-nuxt-app/releases/tag/untagged-61a9ea547c552e870c1e)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: